import { useState, useRef, useMemo, useCallback } from 'react';
import { usePaletteStore } from '../../stores/paletteStore';
import { hexToRgb, rgbToHsl } from '../../utils/colorUtils';
import { useToast } from '../ui/Toast';

type Layout = 'horizontal' | 'vertical' | 'grid';

export default function SharePanel() {
  const { colors, name } = usePaletteStore();
  const { toast } = useToast();
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const [layout, setLayout] = useState<Layout>('horizontal');
  const [showValues, setShowValues] = useState(true);
  const [bgDark, setBgDark] = useState(true);

  const getTextColor = useCallback((hex: string) => {
    const { r, g, b } = hexToRgb(hex);
    const luminance = (0.299 * r + 0.587 * g + 0.114 * b) / 255;
    return luminance > 0.5 ? '#000000' : '#FFFFFF';
  }, []);

  const drawCanvas = useCallback(() => {
    const canvas = canvasRef.current;
    if (!canvas || colors.length === 0) return null;

    const padding = 40;
    const blockGap = 4;
    const valueHeight = showValues ? 32 : 0;
    const headerHeight = 56;
    const footerHeight = 28;

    let canvasWidth: number;
    let canvasHeight: number;
    let blockWidth: number;
    let blockHeight: number;

    if (layout === 'horizontal') {
      canvasWidth = Math.max(600, colors.length * 100 + padding * 2);
      blockWidth = (canvasWidth - padding * 2 - blockGap * (colors.length - 1)) / colors.length;
      blockHeight = 120;
      canvasHeight = padding + headerHeight + blockHeight + valueHeight + footerHeight + padding;
    } else if (layout === 'vertical') {
      canvasWidth = 400;
      blockWidth = canvasWidth - padding * 2;
      blockHeight = 48;
      canvasHeight = padding + headerHeight + (blockHeight + valueHeight + blockGap) * colors.length - blockGap + footerHeight + padding;
    } else {
      const cols = Math.min(colors.length, 3);
      const rows = Math.ceil(colors.length / cols);
      canvasWidth = Math.max(400, cols * 140 + padding * 2);
      blockWidth = (canvasWidth - padding * 2 - blockGap * (cols - 1)) / cols;
      blockHeight = 80;
      canvasHeight = padding + headerHeight + (blockHeight + valueHeight + blockGap) * rows - blockGap + footerHeight + padding;
    }

    canvas.width = canvasWidth * 2;
    canvas.height = canvasHeight * 2;
    canvas.style.width = canvasWidth + 'px';
    canvas.style.height = canvasHeight + 'px';

    const ctx = canvas.getContext('2d')!;
    ctx.scale(2, 2);

    ctx.fillStyle = bgDark ? '#0f1729' : '#ffffff';
    ctx.fillRect(0, 0, canvasWidth, canvasHeight);

    ctx.fillStyle = bgDark ? '#ffffff' : '#1a1a2e';
    ctx.font = 'bold 20px system-ui, -apple-system, sans-serif';
    ctx.textBaseline = 'top';
    ctx.fillText(name || '配色方案', padding, padding);

    ctx.fillStyle = bgDark ? '#8892b0' : '#666';
    ctx.font = '12px system-ui, -apple-system, sans-serif';
    ctx.fillText(`${colors.length} 色 · Control-Color`, padding, padding + 28);

    const startY = padding + headerHeight;

    colors.forEach((color, i) => {
      let x: number, y: number;

      if (layout === 'horizontal') {
        x = padding + i * (blockWidth + blockGap);
        y = startY;
      } else if (layout === 'vertical') {
        x = padding;
        y = startY + i * (blockHeight + valueHeight + blockGap);
      } else {
        const cols = Math.min(colors.length, 3);
        const col = i % cols;
        const row = Math.floor(i / cols);
        x = padding + col * (blockWidth + blockGap);
        y = startY + row * (blockHeight + valueHeight + blockGap);
      }

      ctx.beginPath();
      const radius = 6;
      ctx.roundRect(x, y, blockWidth, blockHeight, radius);
      ctx.fillStyle = color.hex;
      ctx.fill();

      if (showValues) {
        const textColor = getTextColor(color.hex);
        ctx.fillStyle = textColor;
        ctx.font = 'bold 13px monospace';
        ctx.textBaseline = 'middle';
        ctx.fillText(color.hex, x + 10, y + blockHeight / 2);

        ctx.fillStyle = bgDark ? '#8892b0' : '#666';
        ctx.font = '10px monospace';
        ctx.textBaseline = 'top';
        const { r, g, b: bv } = color.rgb;
        const hsl = rgbToHsl(r, g, bv);
        ctx.fillText(
          `RGB(${r},${g},${bv})  HSL(${hsl.h}°,${hsl.s}%,${hsl.l}%)`,
          x,
          y + blockHeight + 4
        );
      }
    });

    ctx.fillStyle = bgDark ? '#4a5568' : '#999';
    ctx.font = '10px system-ui, -apple-system, sans-serif';
    ctx.textBaseline = 'top';
    ctx.fillText('Generated by Control-Color', padding, canvasHeight - padding + 4);

    return canvas;
  }, [colors, name, layout, showValues, bgDark, getTextColor]);

  const handleDownload = () => {
    const canvas = drawCanvas();
    if (!canvas) return;
    canvas.toBlob((blob) => {
      if (!blob) return;
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `control-color-share-${Date.now()}.png`;
      a.click();
      URL.revokeObjectURL(url);
      toast('分享图片已下载', 'success');
    }, 'image/png');
  };

  const handleCopy = async () => {
    const canvas = drawCanvas();
    if (!canvas) return;
    try {
      const blob = await new Promise<Blob | null>((resolve) => canvas.toBlob(resolve, 'image/png'));
      if (!blob) return;
      await navigator.clipboard.write([new ClipboardItem({ 'image/png': blob })]);
      toast('已复制到剪贴板', 'success');
    } catch {
      toast('复制失败，请使用下载按钮', 'error');
    }
  };

  const previewStyle = useMemo(() => {
    if (colors.length === 0) return {};
    const colorStops = colors.map((c, i) => `${c.hex} ${Math.round((i / (colors.length - 1)) * 100)}%`).join(', ');
    return { background: `linear-gradient(90deg, ${colorStops})` };
  }, [colors]);

  if (colors.length === 0) {
    return (
      <div className="flex flex-col gap-4">
        <h3 className="text-sm font-medium text-text-primary">分享配色</h3>
        <p className="text-xs text-text-muted">
          请先添加颜色到配色方案，以生成分享图片。
        </p>
      </div>
    );
  }

  return (
    <div className="flex flex-col gap-4">
      <h3 className="text-sm font-medium text-text-primary">分享配色</h3>
      <p className="text-xs text-text-muted">
        生成精美的配色方案分享图片，适合社交媒体分享。
      </p>

      <div className="flex gap-1 h-10 rounded-lg overflow-hidden border border-border">
        {colors.map((c, i) => (
          <div key={i} className="flex-1" style={{ backgroundColor: c.hex }} />
        ))}
      </div>

      <div className="space-y-2">
        <label className="text-xs text-text-secondary">布局</label>
        <div className="grid grid-cols-3 gap-1">
          {([
            { key: 'horizontal' as const, label: '横向' },
            { key: 'vertical' as const, label: '纵向' },
            { key: 'grid' as const, label: '网格' },
          ]).map(({ key, label }) => (
            <button
              key={key}
              onClick={() => setLayout(key)}
              className={`text-xs py-1.5 rounded-md transition-colors ${
                layout === key
                  ? 'bg-primary text-white'
                  : 'bg-surface border border-border text-text-secondary hover:text-text-primary'
              }`}
            >
              {label}
            </button>
          ))}
        </div>
      </div>

      <div className="flex items-center justify-between">
        <span className="text-xs text-text-secondary">显示色值</span>
        <button
          onClick={() => setShowValues(!showValues)}
          className={`w-9 h-5 rounded-full relative transition-colors ${
            showValues ? 'bg-primary' : 'bg-border'
          }`}
        >
          <div className={`absolute top-0.5 w-4 h-4 rounded-full bg-white transition-transform ${
            showValues ? 'right-0.5' : 'left-0.5'
          }`} />
        </button>
      </div>

      <div className="flex items-center justify-between">
        <span className="text-xs text-text-secondary">背景</span>
        <div className="flex gap-1">
          <button
            onClick={() => setBgDark(true)}
            className={`text-[10px] px-3 py-1 rounded-md transition-colors ${
              bgDark ? 'bg-primary text-white' : 'bg-surface border border-border text-text-secondary'
            }`}
          >
            暗色
          </button>
          <button
            onClick={() => setBgDark(false)}
            className={`text-[10px] px-3 py-1 rounded-md transition-colors ${
              !bgDark ? 'bg-primary text-white' : 'bg-surface border border-border text-text-secondary'
            }`}
          >
            亮色
          </button>
        </div>
      </div>

      <canvas ref={canvasRef} className="w-full rounded-lg border border-border" />

      <div className="flex gap-2">
        <button onClick={handleCopy} className="flex-1 btn-secondary text-xs py-2">
          复制图片
        </button>
        <button onClick={handleDownload} className="flex-1 btn-primary text-xs py-2">
          下载 PNG
        </button>
      </div>
    </div>
  );
}
